# Generated by Django 5.1.6 on 2025-02-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='RochaProductos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'productosRocha',
            },
        ),
    ]
